spring:
  application:
    name: slackbot
    
server:
  port: 9119

slack:
  bot:
    key: yourkey
    channel: random
    name: mycroft
    mycrofturi: 192.168.0.177
    
logging:
  level:
    slacker: DEBUG
    com.ullink.slack: INFO
    
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
